import * as G from "./generators";
import type { Section, Skill } from "./types";

export const SECTIONS: Section[] = [
  { id: "A", name: "Números y contar", icon: "🔢" },
  { id: "B", name: "Sumar", icon: "➕" },
  { id: "C", name: "Estrategias de suma", icon: "🧠" },
  { id: "D", name: "Entrenamiento de competencias de suma", icon: "🏋️" },
  { id: "E", name: "Resta", icon: "➖" },
  { id: "F", name: "Estrategias de resta", icon: "🧩" },
  { id: "G", name: "Entrenamiento de competencias de resta", icon: "🏋️" },
  { id: "H", name: "Operaciones mixtas", icon: "🔀" },
  { id: "I", name: "Comparar y ordenar", icon: "⚖️" },
  { id: "J", name: "Valor posicional", icon: "🧱" },
  { id: "K", name: "Fracciones", icon: "🍕" },
  { id: "L", name: "Medidas y posiciones", icon: "📏" },
  { id: "M", name: "Geometría", icon: "🔷" },
  { id: "N", name: "Patrones", icon: "🎨" },
  { id: "O", name: "Probabilidad", icon: "🎲" },
];

export const SKILLS: Skill[] = [
  { id: "A.1", section: "A", title: "Aprender a contar: hasta 10", icon: "🔢", generate: (r) => G.countObjects(r, 10, true) },
  { id: "A.2", section: "A", title: "Contar hasta 10", icon: "🔢", generate: (r) => G.countObjects(r, 10, false) },
  { id: "A.3", section: "A", title: "Contar de dos en dos", icon: "🔢", generate: (r) => G.skipCount(r, [2]) },
  { id: "A.4", section: "A", title: "Contar de cinco en cinco", icon: "🔢", generate: (r) => G.skipCount(r, [5]) },
  { id: "A.5", section: "A", title: "Contar de diez en diez", icon: "🔢", generate: (r) => G.skipCount(r, [10]) },
  { id: "A.6", section: "A", title: "Contar de dos en dos, de cinco en cinco y de diez en diez", icon: "🔢", generate: (r) => G.skipCount(r, [2, 5, 10]) },
  { id: "A.7", section: "A", title: "Contar según patrones", icon: "🔢", generate: G.countingPattern },
  { id: "A.8", section: "A", title: "Rectas numéricas", icon: "🔢", generate: G.readNumberLine },
  { id: "A.9", section: "A", title: "Contar en una tabla de centenas", icon: "🔢", generate: G.hundredsChartMissing },
  { id: "A.10", section: "A", title: "Contar hacia delante y hacia atrás: hasta 100", icon: "🔢", generate: (r) => G.countUpDown(r, 100) },
  { id: "A.11", section: "A", title: "Estimar hasta la decena más cercana", icon: "🔢", generate: G.estimateToTen },
  { id: "A.12", section: "A", title: "Contar hacia delante y hacia atrás: hasta 1.000", icon: "🔢", generate: (r) => G.countUpDown(r, 1000) },
  { id: "A.13", section: "A", title: "Seleccionar los números pares o impares", icon: "🔢", generate: G.evenOdd },
  { id: "B.1", section: "B", title: "Seleccionar la suma que coincide con el dibujo", icon: "➕", generate: G.addPictureEquation },
  { id: "B.2", section: "B", title: "Operaciones de suma: sumar hasta 10", icon: "➕", generate: (r) => G.addFacts(r, 10) },
  { id: "B.3", section: "B", title: "Conseguir un número con sumas: hasta 10", icon: "➕", generate: (r) => G.makeTargetNumber(r, 10, "+") },
  { id: "B.4", section: "B", title: "Completar sumas: sumar hasta 10", icon: "➕", generate: (r) => G.addMissing(r, 10) },
  { id: "B.5", section: "B", title: "Operaciones de suma: sumar hasta 20", icon: "➕", generate: (r) => G.addFacts(r, 20) },
  { id: "B.6", section: "B", title: "Conseguir un número con sumas: hasta 20", icon: "➕", generate: (r) => G.makeTargetNumber(r, 20, "+") },
  { id: "B.7", section: "B", title: "Operaciones relacionadas de suma", icon: "➕", generate: (r) => G.relatedAdd(r, 20) },
  { id: "B.8", section: "B", title: "Sumar un número de una cifra a uno de dos sin reagrupar", icon: "➕", generate: (r) => G.addTwoDigitOne(r, false) },
  { id: "B.9", section: "B", title: "Sumar un número de una cifra a uno de dos reagrupando", icon: "➕", generate: (r) => G.addTwoDigitOne(r, true) },
  { id: "B.10", section: "B", title: "Sumar números de dos cifras sin reagrupar", icon: "➕", generate: (r) => G.addTwoTwo(r, false) },
  { id: "B.11", section: "B", title: "Sumar números de dos cifras reagrupando", icon: "➕", generate: (r) => G.addTwoTwo(r, true) },
  { id: "B.12", section: "B", title: "Estimar sumas: números de dos cifras", icon: "➕", generate: (r) => G.estimateTwoDigit(r, "+") },
  { id: "C.1", section: "C", title: "Sumar los dobles", icon: "🧠", generate: G.doubles },
  { id: "C.2", section: "C", title: "Sumar usando dobles más uno", icon: "🧠", generate: (r) => G.doublesNear(r, 1) },
  { id: "C.3", section: "C", title: "Sumar usando dobles menos uno", icon: "🧠", generate: (r) => G.doublesNear(r, -1) },
  { id: "C.4", section: "C", title: "Completar sumas hasta llegar a 10", icon: "🧠", generate: G.makeTen },
  { id: "C.5", section: "C", title: "Sumar dos múltiplos de 10", icon: "🧠", generate: G.addTens },
  { id: "C.6", section: "C", title: "Sumar un múltiplo de 10", icon: "🧠", generate: G.addMultipleOfTen },
  { id: "D.1", section: "D", title: "Sumar 1", icon: "🏋️", generate: (r) => G.addK(r, 1) },
  { id: "D.2", section: "D", title: "Sumar 2", icon: "🏋️", generate: (r) => G.addK(r, 2) },
  { id: "D.3", section: "D", title: "Sumar 3", icon: "🏋️", generate: (r) => G.addK(r, 3) },
  { id: "D.4", section: "D", title: "Sumar 4", icon: "🏋️", generate: (r) => G.addK(r, 4) },
  { id: "D.5", section: "D", title: "Sumar 5", icon: "🏋️", generate: (r) => G.addK(r, 5) },
  { id: "D.6", section: "D", title: "Sumar 6", icon: "🏋️", generate: (r) => G.addK(r, 6) },
  { id: "D.7", section: "D", title: "Sumar 7", icon: "🏋️", generate: (r) => G.addK(r, 7) },
  { id: "D.8", section: "D", title: "Sumar 8", icon: "🏋️", generate: (r) => G.addK(r, 8) },
  { id: "D.9", section: "D", title: "Sumar 9", icon: "🏋️", generate: (r) => G.addK(r, 9) },
  { id: "D.10", section: "D", title: "Sumar 0", icon: "🏋️", generate: (r) => G.addK(r, 0) },
  { id: "E.1", section: "E", title: "Seleccionar la resta que coincide con el dibujo", icon: "➖", generate: G.takeawayPictureEquation },
  { id: "E.2", section: "E", title: "Operaciones de resta: hasta 10", icon: "➖", generate: (r) => G.subFacts(r, 10) },
  { id: "E.3", section: "E", title: "Conseguir un número con restas: hasta 10", icon: "➖", generate: (r) => G.makeTargetNumber(r, 10, "−") },
  { id: "E.4", section: "E", title: "Completar la resta: números hasta 10", icon: "➖", generate: (r) => G.subMissing(r, 10) },
  { id: "E.5", section: "E", title: "Operaciones de resta: hasta 18", icon: "➖", generate: (r) => G.subFacts(r, 18) },
  { id: "E.6", section: "E", title: "Conseguir un número con restas: hasta 18", icon: "➖", generate: (r) => G.makeTargetNumber(r, 18, "−") },
  { id: "E.7", section: "E", title: "Operaciones relacionadas de resta", icon: "➖", generate: (r) => G.relatedSub(r, 18) },
  { id: "E.8", section: "E", title: "Restar un número de una cifra a uno de dos, sin llevadas", icon: "➖", generate: (r) => G.subTwoDigitOne(r, false) },
  { id: "E.9", section: "E", title: "Restar un número de una cifra a uno de dos, con llevadas", icon: "➖", generate: (r) => G.subTwoDigitOne(r, true) },
  { id: "E.10", section: "E", title: "Restar dos números de dos cifras, sin llevadas", icon: "➖", generate: (r) => G.subTwoTwo(r, false) },
  { id: "E.11", section: "E", title: "Restar dos números de dos cifras, con llevadas", icon: "➖", generate: (r) => G.subTwoTwo(r, true) },
  { id: "E.12", section: "E", title: "Estimar restas: números de dos cifras", icon: "➖", generate: (r) => G.estimateTwoDigit(r, "−") },
  { id: "F.1", section: "F", title: "Restar dobles", icon: "🧩", generate: G.subDoubles },
  { id: "F.2", section: "F", title: "Restar dos múltiplos de 10", icon: "🧩", generate: G.subTens },
  { id: "F.3", section: "F", title: "Restar un múltiplo de 10", icon: "🧩", generate: G.subMultipleOfTen },
  { id: "G.1", section: "G", title: "Restar 1", icon: "🏋️", generate: (r) => G.subK(r, 1) },
  { id: "G.2", section: "G", title: "Restar 2", icon: "🏋️", generate: (r) => G.subK(r, 2) },
  { id: "G.3", section: "G", title: "Restar 3", icon: "🏋️", generate: (r) => G.subK(r, 3) },
  { id: "G.4", section: "G", title: "Restar 4", icon: "🏋️", generate: (r) => G.subK(r, 4) },
  { id: "G.5", section: "G", title: "Restar 5", icon: "🏋️", generate: (r) => G.subK(r, 5) },
  { id: "G.6", section: "G", title: "Restar 6", icon: "🏋️", generate: (r) => G.subK(r, 6) },
  { id: "G.7", section: "G", title: "Restar 7", icon: "🏋️", generate: (r) => G.subK(r, 7) },
  { id: "G.8", section: "G", title: "Restar 8", icon: "🏋️", generate: (r) => G.subK(r, 8) },
  { id: "G.9", section: "G", title: "Restar 9", icon: "🏋️", generate: (r) => G.subK(r, 9) },
  { id: "G.10", section: "G", title: "Restar 0", icon: "🏋️", generate: (r) => G.subK(r, 0) },
  { id: "H.1", section: "H", title: "Seleccionar la suma o resta que coincide con el dibujo", icon: "🔀", generate: G.pictureEquationMixed },
  { id: "H.2", section: "H", title: "Sumas y restas: maneras de conseguir un número", icon: "🔀", generate: G.mixedTargets },
  { id: "H.3", section: "H", title: "Sumar o restar dobles", icon: "🔀", generate: G.doublesMixed },
  { id: "H.4", section: "H", title: "Familias de operaciones", icon: "🔀", generate: G.factFamily },
  { id: "H.5", section: "H", title: "Operaciones relacionadas de suma y resta: hasta 20", icon: "🔀", generate: G.relatedMixed },
  { id: "H.6", section: "H", title: "Operaciones de suma y resta: hasta 20", icon: "🔀", generate: G.mixedFacts },
  { id: "H.7", section: "H", title: "Completar la suma o resta", icon: "🔀", generate: G.completeEquation },
  { id: "H.8", section: "H", title: "Diez más o diez menos", icon: "🔀", generate: G.tenMoreOrLess },
  { id: "H.9", section: "H", title: "Sumar o restar un múltiplo de 10", icon: "🔀", generate: G.addSubMultipleOfTen },
  { id: "H.10", section: "H", title: "Sumar o restar dos múltiplos de 10", icon: "🔀", generate: G.addSubTens },
  { id: "I.1", section: "I", title: "Comparar números: hasta 10", icon: "⚖️", generate: (r) => G.compareSymbol(r, 10) },
  { id: "I.2", section: "I", title: "Comparar números: hasta 100", icon: "⚖️", generate: (r) => G.compareSymbol(r, 100) },
  { id: "I.3", section: "I", title: "Comparar números: hasta 1.000", icon: "⚖️", generate: (r) => G.compareSymbol(r, 1000) },
  { id: "I.4", section: "I", title: "Ordenar números hasta 100", icon: "⚖️", generate: (r) => G.orderNumbers(r, 100, 4) },
  { id: "I.5", section: "I", title: "Ordenar números hasta 1.000", icon: "⚖️", generate: (r) => G.orderNumbers(r, 1000, 5) },
  { id: "J.1", section: "J", title: "Contar decenas y unidades: hasta 20", icon: "🧱", generate: (r) => G.modelToTensOnes(r, 20) },
  { id: "J.2", section: "J", title: "Modelos de valor posicional: hasta 20", icon: "🧱", generate: (r) => G.modelToNumber(r, 20) },
  { id: "J.3", section: "J", title: "Escribir números como decenas y unidades: hasta 20", icon: "🧱", generate: (r) => G.numberToTensOnes(r, 20) },
  { id: "J.4", section: "J", title: "Contar decenas y unidades: hasta 100", icon: "🧱", generate: (r) => G.modelToTensOnes(r, 100) },
  { id: "J.5", section: "J", title: "Modelos de valor posicional: hasta 100", icon: "🧱", generate: (r) => G.modelToNumber(r, 100) },
  { id: "J.6", section: "J", title: "Escribir números como decenas y unidades: hasta 100", icon: "🧱", generate: (r) => G.numberToTensOnes(r, 100) },
  { id: "K.1", section: "K", title: "Mitades, tercios, cuartos", icon: "🍕", generate: G.halvesThirdsFourths },
  { id: "K.2", section: "K", title: "Fracciones simples: partes de un todo", icon: "🍕", generate: (r) => G.fractionOfShape(r, "circle", 4) },
  { id: "K.3", section: "K", title: "Fracciones simples: partes de un grupo", icon: "🍕", generate: G.fractionOfGroup },
  { id: "K.4", section: "K", title: "Comprender las fracciones: barras de fracciones", icon: "🍕", generate: (r) => G.fractionOfShape(r, "bar", 8) },
  { id: "K.5", section: "K", title: "Comprender las fracciones: modelos con áreas", icon: "🍕", generate: (r) => G.fractionOfShape(r, "area", 8) },
  { id: "K.6", section: "K", title: "Mostrar fracciones: barras de fracciones", icon: "🍕", generate: (r) => G.shadeFraction(r, "bar") },
  { id: "K.7", section: "K", title: "Mostrar fracciones: modelos con áreas", icon: "🍕", generate: (r) => G.shadeFraction(r, "area") },
  { id: "K.8", section: "K", title: "Fracciones de rectas numéricas: fracciones unitarias", icon: "🍕", generate: (r) => G.fractionOnLine(r, true) },
  { id: "K.9", section: "K", title: "Fracciones de rectas numéricas", icon: "🍕", generate: (r) => G.fractionOnLine(r, false) },
  { id: "L.1", section: "L", title: "Medir con objetos", icon: "📏", generate: G.measureWithObjects },
  { id: "L.2", section: "L", title: "Medir con una regla", icon: "📏", generate: G.measureWithRuler },
  { id: "L.3", section: "L", title: "Leer un termómetro", icon: "📏", generate: G.readThermometer },
  { id: "L.4", section: "L", title: "Comparar longitudes", icon: "📏", generate: G.compareLengths },
  { id: "L.5", section: "L", title: "Ubicación en una cuadrícula", icon: "📏", generate: G.gridPosition },
  { id: "L.6", section: "L", title: "Encima y debajo", icon: "📏", generate: G.aboveBelow },
  { id: "L.7", section: "L", title: "Relacionar unidades de tiempo", icon: "📏", generate: G.timeUnits },
  { id: "L.8", section: "L", title: "Objetos en un plano de coordenadas", icon: "📏", generate: G.coordinatePlane },
  { id: "M.1", section: "M", title: "Comparar lados y vértices", icon: "🔷", generate: G.compareSidesVertices },
  { id: "M.2", section: "M", title: "Identificar figuras de dos dimensiones", icon: "🔷", generate: G.identifyShape2d },
  { id: "M.3", section: "M", title: "Comparar aristas, vértices y caras", icon: "🔷", generate: G.compareSolidParts },
  { id: "M.4", section: "M", title: "Identificar figuras tridimensionales", icon: "🔷", generate: G.identifySolid },
  { id: "M.5", section: "M", title: "Figuras de objetos de la vida diaria", icon: "🔷", generate: G.everydayObjects },
  { id: "M.6", section: "M", title: "Identificar figuras trazadas a partir de cuerpos sólidos", icon: "🔷", generate: G.tracedShapes },
  { id: "M.7", section: "M", title: "Identificar las caras de figuras tridimensionales", icon: "🔷", generate: G.solidFaces },
  { id: "N.1", section: "N", title: "Completar un patrón", icon: "🎨", generate: G.completePattern },
  { id: "N.2", section: "N", title: "Crear un patrón", icon: "🎨", generate: G.createPattern },
  { id: "N.3", section: "N", title: "Secuencias numéricas crecientes", icon: "🎨", generate: (r) => G.numberSequence(r, true) },
  { id: "N.4", section: "N", title: "Secuencias numéricas decrecientes", icon: "🎨", generate: (r) => G.numberSequence(r, false) },
  { id: "O.1", section: "O", title: "Más probable, menos probable e igual de probable", icon: "🎲", generate: G.moreLikely },
  { id: "O.2", section: "O", title: "Seguro, probable, improbable e imposible", icon: "🎲", generate: G.certainOrImpossible },
];

export function getSkill(id: string) {
  return SKILLS.find((s) => s.id === id);
}
